{{- range $name, $service := .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    {{- include "meshperf.labels" $ | nindent 4 }}
    app.kubernetes.io/name: {{ $name }}
spec:
  replicas: {{ default 1 $service.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ $name }}
        app.kubernetes.io/part-of: meshperf
      {{- if $.Values.sidecar.enabled }}
      annotations:
        sidecar.istio.io/inject: "true"
      {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 100
        runAsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: {{ $name }}
          image: "{{ $service.image.repository }}@{{ $service.image.digest }}"
          imagePullPolicy: {{ $.Values.global.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SERVER_PORT
              value: "8080"
            - name: IMAGE_DIGEST
              value: {{ $service.image.digest | quote }}
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:InitialRAMPercentage=25 -XX:MaxRAMPercentage=75"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ $.Values.global.otelEndpoint | quote }}
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: http/protobuf
            - name: OTEL_TRACES_EXPORTER
              value: otlp
            - name: OTEL_METRICS_EXPORTER
              value: none
            - name: OTEL_LOGS_EXPORTER
              value: none
            - name: TRACING_SAMPLING_PROBABILITY
              value: {{ $.Values.global.tracingSamplingProbability | quote }}
            {{- range $key, $value := $service.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 12
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 36
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            {{- toYaml $service.resources | nindent 12 }}
{{- end }}
