{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: meshperf
spec:
  namespaceSelector:
    matchNames: [{{ .Release.Namespace }}]
  selector:
    matchLabels:
      meshperf.io/metrics: "true"
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
