alertmanager:
  enabled: false

grafana:
  nodeSelector:
    kubernetes.io/hostname: mesh-cp-01
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  persistence:
    enabled: true
    storageClassName: local-path
    size: 1Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 384Mi
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki.observability.svc.cluster.local:3100
      access: proxy
    - name: Tempo
      type: tempo
      url: http://tempo.observability.svc.cluster.local:3200
      access: proxy

prometheusOperator:
  nodeSelector:
    kubernetes.io/hostname: mesh-cp-01
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
  resources:
    requests:
      cpu: 50m
      memory: 96Mi
    limits:
      cpu: 300m
      memory: 256Mi

kube-state-metrics:
  nodeSelector:
    kubernetes.io/hostname: mesh-cp-01
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    retention: 24h
    retentionSize: 2GB
    nodeSelector:
      kubernetes.io/hostname: mesh-cp-01
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
      limits:
        cpu: "1"
        memory: 1536Mi
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 3Gi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 150m
      memory: 96Mi
